openapi: 3.2.0
info:
  title: Mesh Connect Integration Broker Account Detail API
  description: 'Mesh allows users to connect accounts of financial institutions,

    crypto exchanges, and self-custody wallets. Mesh handles credential

    validation, MFA, and error handling for each integration. After

    an account is connected, Mesh allows client applications to read holdings,

    transaction history and balances and execute crypto transfers (with user approval).'
  version: '1.0'
servers:
- url: https://integration-api.meshconnect.com
security:
- Client-Secret: []
  Client-Id: []
tags:
- name: BrokerAccountDetail
paths:
  /api/v1/account/verify:
    post:
      tags:
      - BrokerAccountDetail
      summary: Verify account identity
      description: Return KYC details of the user.
      requestBody:
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/B2BBrokerAccountDetailsRequest'
            example:
              authToken: Secret authentication token
              integrationId: 4d3364d9-fa09-4382-ad4e-5cab2e355fd4
      responses:
        '200':
          description: Successfully returns account details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/B2BBrokerAccountDetailsResponseApiResult'
              example:
                content:
                  firstName: Firstname
                  middleName: Midlename
                  lastName: Lastname
                  accountNumber: '1234567'
                  email: enduser@domain.com
                  mobileNumber: '123456798'
                  companyName: MyCorp Inc.
                  integrationName: Coinbase
                  countryCode: GB
                  city: City Name
                  postalCode: '4251'
                  idType: idCard
                  idNumber: '123'
                  dateOfBirth: 574732800
                status: ok
                message: ''
                errorType: ''
        '400':
          description: Request to retrieve account details is not correct.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResult'
              example:
                status: badRequest
                message: Error message
                displayMessage: Optional display message
                errorType: missingField
        '401':
          description: 'Unauthorized: Client Id or Client Secret are not correct or missing.'
          content:
            application/json:
              schema: {}
        '403':
          description: Forbidden
          content:
            application/json:
              schema: {}
      operationId: postApiV1AccountVerify
      x-operation-id-source: derived
components:
  schemas:
    B2BBrokerAccountDetailsResponse:
      type: object
      properties:
        firstName:
          type:
          - string
          - 'null'
        middleName:
          type:
          - string
          - 'null'
        lastName:
          type:
          - string
          - 'null'
        accountNumber:
          type:
          - string
          - 'null'
        email:
          type:
          - string
          - 'null'
        mobileNumber:
          type:
          - string
          - 'null'
        companyName:
          type:
          - string
          - 'null'
        integrationName:
          type:
          - string
          - 'null'
        countryCode:
          type:
          - string
          - 'null'
        city:
          type:
          - string
          - 'null'
        postalCode:
          type:
          - string
          - 'null'
        address:
          type:
          - string
          - 'null'
        idType:
          enum:
          - none
          - idCard
          - driversLicense
          - passport
          allOf:
          - $ref: '#/components/schemas/UserIdentificationType'
        idNumber:
          type:
          - string
          - 'null'
        dateOfBirth:
          type:
          - integer
          - 'null'
          format: int64
      additionalProperties: false
    ApiResultStatus:
      enum:
      - ok
      - serverFailure
      - permissionDenied
      - badRequest
      - notFound
      - conflict
      - tooManyRequest
      - locked
      type: string
    B2BBrokerAccountDetailsResponseApiResult:
      type: object
      properties:
        status:
          enum:
          - ok
          - serverFailure
          - permissionDenied
          - badRequest
          - notFound
          - conflict
          - tooManyRequest
          - locked
          allOf:
          - $ref: '#/components/schemas/ApiResultStatus'
          readOnly: true
        message:
          type:
          - string
          - 'null'
          description: A message generated by the API
        displayMessage:
          type:
          - string
          - 'null'
          description: User-friendly display message that can be presented to the end user
        errorType:
          type:
          - string
          - 'null'
          description: 'Strictly-typed error type that is explaining the reason of an unsuccessful status of the operation.

            All possible error types are available in the documentation.'
        errorData:
          readOnly: true
        content:
          allOf:
          - $ref: '#/components/schemas/B2BBrokerAccountDetailsResponse'
      additionalProperties: false
    UserIdentificationType:
      enum:
      - none
      - idCard
      - driversLicense
      - passport
      type: string
    ApiResult:
      type: object
      properties:
        status:
          enum:
          - ok
          - serverFailure
          - permissionDenied
          - badRequest
          - notFound
          - conflict
          - tooManyRequest
          - locked
          allOf:
          - $ref: '#/components/schemas/ApiResultStatus'
          readOnly: true
        message:
          type:
          - string
          - 'null'
          description: A message generated by the API
        displayMessage:
          type:
          - string
          - 'null'
          description: User-friendly display message that can be presented to the end user
        errorType:
          type:
          - string
          - 'null'
          description: 'Strictly-typed error type that is explaining the reason of an unsuccessful status of the operation.

            All possible error types are available in the documentation.'
        errorData:
          readOnly: true
      additionalProperties: false
    B2BBrokerAccountDetailsRequest:
      required:
      - authToken
      - integrationId
      type: object
      properties:
        authToken:
          minLength: 1
          type: string
          description: Auth token that allows connecting to the target institution.
        integrationId:
          type: string
          description: The Id which uniquely identifies the integration.
          format: uuid
      additionalProperties: false
  securitySchemes:
    Client-Secret:
      type: apiKey
      description: Contact Mesh to get client Secret
      name: X-Client-Secret
      in: header
    Client-Id:
      type: apiKey
      description: Contact Mesh to get client Id
      name: X-Client-Id
      in: header
